### ISSUE TITLE
Weather Map animationDidReset: Crash

### ISSUE THREAD

**Issue by iwxxcz** [aerisweather/Aeris-iOS-Library#1]
Going in background while weather map animation going causing to crash. 

How to reproduce on Demo Application:
1. Open app.
2. Load controller with Apple Map.
3. Start weather animation.
4. Go back to main menu.
5. Close app leaving it in background.
6. Re-open it.

**Comment by u10int** [comment]
@iwxxcz Do you have a stack trace or crash log leading up to the crash?

**Comment by iwxxcz** [comment]
[AerisSDKDemo  2016-04-24, 1-46 AM.txt](https://github.com/aerisweather/Aeris-iOS-Library/files/233186/AerisSDKDemo.2016-04-24.1-46.AM.txt)

**Comment by iwxxcz** [comment]
[AerisSDKDemo  2016-04-24, 1-46 AM.txt](https://github.com/aerisweather/Aeris-iOS-Library/files/233187/AerisSDKDemo.2016-04-24.1-46.AM.txt)

**Comment by u10int** [comment]
I just released 2.3.1 of the SDK with several fixes for cancelling and resetting the animation processes when either the parent view controller disappears or app goes into the background. I just repeated your steps and wasn't able to reproduce this crash after these fixes, so it looks like it was related.
