### ISSUE TITLE
I want to add below overlay animation(flowing) .Please find the attached

### ISSUE THREAD

**Issue by pawanline** [aerisweather/Aeris-iOS-Library#11]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15170689/77308813-8de27b80-6d21-11ea-8612-a1d25a6f270b.gif)
I have tried with the below properites
`  self.animationCrossfadeEnabled = true
        self.timelineEndOffsetFromNow = 7200
        self.timelineStartOffsetFromNow = 7200
        self.animationEndDelay = 3
        self.maximumIntervalsForAnimation = 2
        self.showAnimationLoadingProgress = true
        self.animationDuration = 3.0`

**Comment by pawanline** [comment]
@u10int  Please look into this as soon as possible .Using the same property is working in android SDK.

**Comment by pawanline** [comment]
@u10int  Please look into this.
I tried with these properties also as , timelineStartOffsetFromNow and  timelineEndOffsetFromNow cannot be same
     self.refreshInterval = 2 * AWFSecondInterval
//        self.showsCountyLines = true
        
        self.animationEnabled = true
        self.timelineEndOffsetFromNow = Date().timeIntervalSinceNow
        self.timelineStartOffsetFromNow = -2 * AWFSecondInterval
        self.animationEndDelay = 0.0
        self.timelineScrubbingEnabled = true
        self.maximumIntervalsForAnimation = 20
        self.animationDuration = 1

**Comment by u10int** [comment]
@pawanline Not sure I understand your comment about "I want to add below overlay animation(flowing)". Can you elaborate more on this?

**Comment by pawanline** [comment]
Please have a look at my approach 
https://github.com/pawanline/KMLAFWeatherMap

**Comment by u10int** [comment]
If you're just wanting an animation similar to that in your screen capture, then you should be able to use the default AWFWeatherMapConfig settings. Note that `timelineStartOffsetFromNow` and `timelineEndOffsetFromNow` should be set to the number of seconds relative to now you want for the timeline range. If these are the same value, then the data won't animation. 

In your code above, you're setting `timelineStartOffsetFromNow` to `-2 * AWFSecondInterval`, which means you want the timeline to start two seconds ago. This is essentially the same as now which won't work. You need to use `AWFHourInterval` instead to start the timeline two hours ago relative to now: 

```
self.timelineStartOffsetFromNow = -2 * AWFHourInterval
self.timelineEndOffsetFromNow = 0
```

**Comment by pawanline** [comment]
Do i need to change other properties? its still not working  can you please have a look at my approach?.

**Comment by u10int** [comment]
Can you remove all other properties you've overridden so that just the default values from AWFWeatherMapConfig are used and see if that works? In your code above, you're also setting `self.animationDuration = 10`, which means you want the entire animation loop to take 10 seconds to complete. This will result in a slow and choppy animation, so you'll want this value to be something more like `self.animationDuration = 2`.

**Comment by pawanline** [comment]
Ok

**Comment by pawanline** [comment]
I have removed all the the properties . still not working .There is  KML layer also in the prjoject.Will this affect ?
class OutageWeatherMapConfig: AWFWeatherMapConfig {
    
    override init() {
        super.init()

        self.timelineStartOffsetFromNow = -2 * AWFHourInterval
        self.timelineEndOffsetFromNow = 0
    }
}

**Comment by pawanline** [comment]
@u10int  have you checked ?

**Comment by u10int** [comment]
Are you referring to no weather data showing up on the map, or just the animation not working? I tested the project from your linked repo and I get the following error in the console:

```
2020-03-23 07:28:27.780914-0700 KMLAFweatherMap[29015:16157770] [Aeris] ERROR Error Domain=com.aerisweather.weather.errors Code=501 "The client provided is not authorized to access the request." UserInfo={NSLocalizedDescription=The client provided is not authorized to access the request.}
2020-03-23 07:28:27.781103-0700 KMLAFweatherMap[29015:16157770] [Aeris] ERROR Account permissions request failed: The client provided is not authorized to access the request.
```

This error means the AerisWeather access keys (client id and secret) you're using aren't set up under your Aeris account for the bundle identifier of your app. Make sure you have added `com.sew.KMLAFweatherMap` to the registered application under your account at https://www.aerisweather.com/account

**Comment by pawanline** [comment]
just the animation

**Comment by pawanline** [comment]
I am workin on live project.

**Comment by pawanline** [comment]
Apologies, I can share keys. did you get anything?

**Comment by pawanline** [comment]
@u10int .Please find the project with test-client and secret key.

**Comment by pawanline** [comment]
https://github.com/pawanline/KMLAFWeatherMap

**Comment by u10int** [comment]
@pawanline When testing using your updated access keys, I'm getting an error for all AMP tile requests about you being over your daily access limit. Thus no weather tiles are being loaded at this time: 

```
{
  "error": {
    "code": "authorization_error",
    "message": "This client does not have access to the Aeris Maps Platform: Maximum number of daily accesses reached."
  }
}
```

You'll either need to wait until your accesses reset (at midnight GMT) or upgrade your subscription to provide a higher daily access limit.

**Comment by pawanline** [comment]
@U10int It’s urgent , please use these keys 

9oZsgR3UiOib88MGnnEkG

8u4Cc2dqJu9e8yszJzKWfmYl5ysq8MP09JW0gvdy

**Comment by u10int** [comment]
You're UISwitch change event handler is not using the right methods for starting/stoping the animation. Your app is using this currently: 

```
@IBAction func overlayLoopChanged(_ sender: UISwitch) {
        if sender.isOn {
            afWeatherMapView.enableAutoRefresh()
        } else {
            afWeatherMapView.disableAutoRefresh()
        }
    }
```

But it should be:
```
@IBAction func overlayLoopChanged(_ sender: UISwitch) {
        if sender.isOn {
			afWeatherMapView.startAnimating()
        } else {
			afWeatherMapView.startAnimating()
        }
    }
```

**Comment by pawanline** [comment]
@u10int  . thanks its working with these keys. I found the issue , basically it is with keys when I am using my live project keys Its not  working . can you please tell me?. I think we have to configure sdk . One more thing its not working with maptype apple but same working with google.
    let afWeatherMapView = AWFWeatherMap(mapType: .apple,config: MyWeatherAppConfig())

**Comment by u10int** [comment]
The issue with animation not working was primarily due to the code I referenced in my last response where you were enabled/disabling auto refresh when the UISwitch was toggled instead of starting/stopping the animation. 

I had no issue getting it to work with the map type set to `.apple`. Can you elaborate on what the exact issue is?

**Comment by pawanline** [comment]
It was issue with namespace of AerisWeatherSDK portal . Thanks for your support.
