### ISSUE TITLE
Swift Project

### ISSUE THREAD

**Issue by EvandroViva** [aerisweather/Aeris-iOS-Library#2]
Do you have any swift demo project with pods using your SDK? I could not install

**Comment by u10int** [comment]
@EvandroViva We just added a basic demo project in Swift that integrates with our SDK: https://github.com/aerisweather/Aeris-iOS-Library/tree/master/Demo

The main requirement when using our SDK in Swift is to include a bridging header, which you can see in this Swift project example: https://github.com/aerisweather/Aeris-iOS-Library/blob/master/Demo/Swift/AerisSDKDemo-Swift/AerisSDKDemo-Swift-Bridging-Header.h

Here's more information regarding setting up a bridging header for Swift projects: https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
