### ISSUE TITLE
NSObject/NSCoding compile errors

### ISSUE THREAD

**Issue by VictorZyabko** [aerisweather/Aeris-iOS-Library#3]
After adding iOS SDK to my xCode project, i'm gettings errors in all my classes inherited from NSObject:

....swift:16:1: 'required' initializer 'init(coder:)' must be provided by subclass of 'NSObject'

Although i don't use NSCoding interface.

**Comment by u10int** [comment]
Can you provide more details about the issue:

What version of Swift are you using? 
Do you have the same issue when running the Swift demo provided by this repo? 
What classes are the errors coming from, those from our SDK or from your own project's classes?

init(coder:) is a designated initializer for NSObject and any classes that subclass it, so if you have custom objects in your project that subclass NSObject, you'll also need to implement init(coder:) in them.

**Comment by VictorZyabko** [comment]
In the Swift demo project i have the issue too when adding ": NSObject" class.

For example inherit this class:
class MenuItem {
	var title: String
	var controller: UIViewController
	
	init(title: String, controller: UIViewController) {
		self.title = title
		self.controller = controller
	}
}
->

class MenuItem: NSObject {
	var title: String
	var controller: UIViewController
	
	init(title: String, controller: UIViewController) {
		self.title = title
		self.controller = controller
	}
}

-> 
Error:
.../Aeris-iOS-Library-master/Demo/AerisSwiftDemo/ViewController.swift:19:1: 'required' initializer 'init(coder:)' must be provided by subclass of 'NSObject'

**Comment by VictorZyabko** [comment]
init(coder:) is from interface NSCoding. Not NSObject.
I have old project mixed of Objective-C and Swift, and never had to implement init(coder:)

**Comment by u10int** [comment]
This is not a bug with the SDK but due to you making MenuItem a subclass of NSObject, which has a requirement that all subclasses must implement init(coder:) when using Swift. All required initializes must be implemented in their subclasses.

https://stackoverflow.com/questions/35255466/swift-error-required-initializer-initcoder-must-be-provided-by-subclas

**Comment by u10int** [comment]
Ah, I see the issue now and was able to reproduce. We'll investigate it further and post back once we dig into our code more.

**Comment by u10int** [comment]
Thanks for letting us know about this issue. We have corrected it in our SDK and verified subclassing NSObject via Swift no longer gives the required initializer error and will be pushing out 3.0.7 with the fix this afternoon. I'll post back here once it's available.

**Comment by u10int** [comment]
3.0.7 is out with the fix for this issue, and our tests confirm the error for Swift no longer occurs: https://www.aerisweather.com/support/docs/toolkits/aeris-ios-sdk/reference/versions/#3.0.7
