### ISSUE TITLE
didn't find any way to set AWFWeatherDataType.need  suggestion .

### ISSUE THREAD

**Issue by pawanline** [aerisweather/Aeris-iOS-Library#7]
I am creating map like below.
  let afWeatherMapView = AWFWeatherMap(mapType: .apple, config: MyWeatherMapConfig())

**Comment by pawanline** [comment]
i am setting properties like  below.
       afWeatherMapView.mapView.backgroundColor = .blue
        afWeatherMapView.mapViewDelegate = self
        afWeatherMapView.animationRepeatCount = -1

**Comment by u10int** [comment]
@pawanline What are you trying to accomplish? `AWFWeatherDataType` doesn't get used directly with an `AWFWeatherMap` instance: https://www.aerisweather.com/docs/ios/AerisWeatherKit/Other%20Enums.html#/c:@E@AWFWeatherDataType

**Comment by pawanline** [comment]
Ok got it thanks
