### ISSUE TITLE
data source method not calling .

### ISSUE THREAD

**Issue by pawanline** [aerisweather/Aeris-iOS-Library#8]

**Comment by u10int** [comment]
@pawanline You're going to need to provide specific details about the issue you're having, such as which data source and which methods as well as your implementation.

**Comment by pawanline** [comment]
@u10int Please check this project 
https://github.com/pawanline/KMLAFWeatherMap
on view controller class  line 37 I have set datasource  to self.
but still datasource method not called line 98  -  109

**Comment by u10int** [comment]
What are you trying to accomplish with those data source methods? I set breakpoints in your data source method implementations and they are getting called properly. Not all of them will get called based on your current code as some are dependent upon specific features and/or layers of the weather map.
